import type {
  User,
  Space,
  Resource,
  EventScreening,
  Booking,
  Loan,
  Incident,
  DashboardStats,
} from '../../apps/web/src/types';

export const mockUserStudent: User = {
  id: 'usr-student-001',
  email: 'ernesto.fierro@alumnos.udg.mx',
  nombre: 'Ernesto Hatuey Fierro Meléndez',
  codigo: '215789456',
  rol: 'ESTUDIANTE',
  carrera: 'Ingeniería en Ciencias Computacionales',
  telefono: '3312345678',
  reputationScore: 100,
};

export const mockUserAdmin: User = {
  id: 'usr-admin-001',
  email: 'admin.sigre@udg.mx',
  nombre: 'Coordinación General de Tecnologías',
  codigo: 'ADMIN-CUT-001',
  rol: 'ADMIN',
  reputationScore: 100,
};

export const mockSpaces: Space[] = [
  {
    id: 'sp-auditorio',
    nombre: 'Auditorio Principal CUTonalá',
    codigoEspacio: 'AUD-PRIN-01',
    edificio: 'Edificio de Rectoría',
    piso: 'Planta Baja',
    capacidad: 350,
    tipo: 'AUDITORIO',
    activo: true,
    equipamiento: ['Audio Profesional Shure', 'Proyector 4K 10,000 lm', 'Cabina de Transmisión', 'Aire Acondicionado'],
    fotos: [],
    reglamento: 'Solicitud con mínimo 3 días de antelación. No ingresar alimentos ni bebidas.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sp-cineteca',
    nombre: 'Cineteca CUTonalá (Sala Guillermo del Toro)',
    codigoEspacio: 'CIN-DEL-TORO',
    edificio: 'Edificio C',
    piso: 'Piso 1',
    capacidad: 120,
    tipo: 'CINETECA',
    activo: true,
    equipamiento: ['Sonido Envolvente Dolby 7.1', 'Proyector Láser Cine DCI', 'Butacas Reclinables'],
    fotos: [],
    reglamento: 'Acceso exclusivo con boleto digital QR. Prohibido grabar la función.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sp-lab-ia',
    nombre: 'Laboratorio de Inteligencia Artificial y Cómputo Avanzado',
    codigoEspacio: 'LAB-IA-204',
    edificio: 'Edificio de Ingenierías',
    piso: 'Piso 2',
    capacidad: 40,
    tipo: 'LABORATORIO',
    activo: true,
    equipamiento: ['40 Workstations con GPU RTX', 'Pizarrón Interactivo Smart', 'Climatización Controlada'],
    fotos: [],
    reglamento: 'Uso exclusivo para proyectos académicos y de investigación aprobados.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sp-aula-magna',
    nombre: 'Aula Magna A-101',
    codigoEspacio: 'AUL-MAG-101',
    edificio: 'Edificio A',
    piso: 'Planta Baja',
    capacidad: 90,
    tipo: 'AULA',
    activo: true,
    equipamiento: ['Pantalla Motorizada', 'Audio Ambiental', 'Micrófono de Cuello de Ganso'],
    fotos: [],
    reglamento: 'Reservas asignadas por Coordinación de Control Escolar.',
    created_at: new Date().toISOString(),
  },
];

export const mockResources: Resource[] = [
  {
    id: 'res-thinkpad-14',
    nombre: 'Laptop Lenovo ThinkPad T14 Gen 3 (Core i7 / 32GB RAM)',
    codigoInventario: 'UDG-CUT-ING-0891',
    categoria: 'COMPUTO',
    marca: 'Lenovo',
    modelo: 'ThinkPad T14 Gen 3',
    numeroSerie: 'PF-3982KL-2024',
    estado: 'DISPONIBLE',
    condicionFisica: 'EXCELENTE',
    ubicacion: 'Almacén de Ingenierías (Módulo B)',
    diasMaxPrestamo: 3,
    requiereCapacitacion: false,
    horasUsoTotales: 142,
  },
  {
    id: 'res-epson-laser',
    nombre: 'Videoproyector Láser Epson PowerLite L530U (5200 lm)',
    codigoInventario: 'UDG-CUT-AV-0412',
    categoria: 'AUDIOVISUAL',
    marca: 'Epson',
    modelo: 'PowerLite L530U',
    numeroSerie: 'EP-991204-X',
    estado: 'DISPONIBLE',
    condicionFisica: 'EXCELENTE',
    ubicacion: 'Audiovisual Central (Rectoría)',
    diasMaxPrestamo: 1,
    requiereCapacitacion: false,
    horasUsoTotales: 89,
  },
  {
    id: 'res-shure-mic',
    nombre: 'Sistema de Micrófonos Inalámbricos Dobles Shure BLX288/PG58',
    codigoInventario: 'UDG-CUT-AV-0550',
    categoria: 'AUDIOVISUAL',
    marca: 'Shure',
    modelo: 'BLX288/PG58',
    numeroSerie: 'SH-812033-US',
    estado: 'DISPONIBLE',
    condicionFisica: 'BUENO',
    ubicacion: 'Audiovisual Central (Rectoría)',
    diasMaxPrestamo: 1,
    requiereCapacitacion: false,
    horasUsoTotales: 64,
  },
  {
    id: 'res-arduino-kit',
    nombre: 'Maletín Kit Robótica Avanzada Arduino Mega + Shield IoT',
    codigoInventario: 'UDG-CUT-ROB-0115',
    categoria: 'LABORATORIO',
    marca: 'Arduino',
    modelo: 'Mega 2560 Pro Kit',
    numeroSerie: 'ARD-MEGA-2025-09',
    estado: 'DISPONIBLE',
    condicionFisica: 'EXCELENTE',
    ubicacion: 'Laboratorio de Electrónica y Robótica',
    diasMaxPrestamo: 7,
    requiereCapacitacion: true,
    horasUsoTotales: 210,
  },
];

export const mockScreenings: EventScreening[] = [
  {
    id: 'scr-macario',
    titulo: 'Macario (1960) — Versión Restaurada 4K',
    sinopsis: 'Un humilde campesino obsesionado con comer un banquete solo para él recibe tres tentaciones sobrenaturales en la víspera de Día de Muertos. Obra cumbre del cine mexicano nominada al Óscar.',
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    trailerUrl: 'https://www.youtube.com/watch?v=mock-macario',
    clasificacion: 'B',
    duracionMin: 91,
    director: 'Roberto Gavaldón',
    fechaHoraInicio: '2026-10-10T17:00:00.000Z',
    fechaHoraFin: '2026-10-10T19:00:00.000Z',
    cupoMaximo: 120,
    asientosDisponibles: 48,
    espacio: {
      id: 'sp-cineteca',
      nombre: 'Cineteca CUTonalá (Sala Guillermo del Toro)',
      edificio: 'Edificio C',
    },
  },
];

export const mockLoans: Loan[] = [
  {
    id: 'loan-1',
    folio: 'PREST-2026-0041',
    fechaInicio: '2026-10-01T10:00:00.000Z',
    fechaLimiteDevolucion: '2026-10-04T18:00:00.000Z',
    fechaDevolucionReal: '2026-10-04T16:30:00.000Z',
    estado: 'DEVUELTO',
    esPrestamoExtendido: false,
    recurso: mockResources[0],
    solicitante: mockUserStudent,
    responsivaHash: 'SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    checklistSalida: {
      condicion: 'EXCELENTE',
      accesoriosEntregados: ['Cargador 65W USB-C', 'Funda acolchada'],
      observaciones: 'Equipo verificado al 100% de batería y sin rasguños.',
    },
    checklistEntrada: {
      condicion: 'EXCELENTE',
      accesoriosDevueltos: ['Cargador 65W USB-C', 'Funda acolchada'],
      observaciones: 'Recepción conforme en almacén. Sin daño físico.',
    },
  },
  {
    id: 'loan-2',
    folio: 'PREST-2026-0089',
    fechaInicio: '2026-10-05T09:00:00.000Z',
    fechaLimiteDevolucion: '2026-10-08T18:00:00.000Z',
    fechaDevolucionReal: null,
    estado: 'ACTIVO',
    esPrestamoExtendido: true,
    recurso: mockResources[3],
    solicitante: mockUserStudent,
    responsivaHash: 'SHA256:4a5b6c7d8e9f0123456789abcdef0123456789abcdef0123456789abcdef0123',
    checklistSalida: {
      condicion: 'EXCELENTE',
      accesoriosEntregados: ['Maletín', 'Cables Jumper', 'Sensores IoT'],
      observaciones: 'Verificado por técnico de laboratorio Roberto Velázquez.',
    },
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'book-1',
    folio: 'SOL-ESP-2026-0012',
    fechaInicio: '2026-10-12T10:00:00.000Z',
    fechaFin: '2026-10-12T13:00:00.000Z',
    estado: 'APROBADA',
    motivoUso: 'Coloquio de Inteligencia Artificial y Sistemas Distribuidos CUTonalá 2026',
    asistentesEstimados: 180,
    espacio: mockSpaces[0],
    solicitante: mockUserStudent,
    created_at: '2026-10-02T12:00:00.000Z',
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'inc-1',
    folio: 'INC-2026-0003',
    tipo: 'DAÑO_EQUIPO',
    gravedad: 'LEVE',
    puntosSancion: 5,
    descripcion: 'Desgaste y falso contacto en cable HDMI de proyector aula 101.',
    estado: 'RESUELTA',
    recurso: {
      id: 'res-epson-laser',
      nombre: 'Videoproyector Láser Epson PowerLite L530U',
      codigoInventario: 'UDG-CUT-AV-0412',
    },
    usuarioInfractor: mockUserStudent,
    created_at: '2026-09-28T14:30:00.000Z',
  },
];

export const mockDashboardStats: DashboardStats = {
  resumen: {
    totalEspacios: 4,
    totalRecursos: 48,
    reservasActivas: 7,
    prestamosActivos: 12,
    incidentesPendientes: 1,
    reservasPendientesAprobacion: 2,
  },
  matrizDesgaste: [
    {
      id: 'res-thinkpad-14',
      nombre: 'Laptop ThinkPad T14 Gen 3',
      codigo: 'UDG-CUT-ING-0891',
      categoria: 'COMPUTO',
      condicion: 'EXCELENTE',
      horasUso: 142,
      vecesPrestado: 18,
      riesgoFalla: 'BAJO',
    },
    {
      id: 'res-epson-laser',
      nombre: 'Videoproyector Láser Epson',
      codigo: 'UDG-CUT-AV-0412',
      categoria: 'AUDIOVISUAL',
      condicion: 'EXCELENTE',
      horasUso: 89,
      vecesPrestado: 12,
      riesgoFalla: 'BAJO',
    },
    {
      id: 'res-shure-mic',
      nombre: 'Micrófono Inalámbrico Shure BLX288',
      codigo: 'UDG-CUT-AV-0550',
      categoria: 'AUDIOVISUAL',
      condicion: 'BUENO',
      horasUso: 320,
      vecesPrestado: 34,
      riesgoFalla: 'MEDIO',
    },
  ],
  ocupacionEspaciosHoy: [
    {
      id: 'sp-auditorio',
      nombre: 'Auditorio Principal',
      edificio: 'Rectoría',
      capacidad: 350,
      reservasHoy: 2,
      ocupadoActualmente: false,
    },
    {
      id: 'sp-cineteca',
      nombre: 'Cineteca CUTonalá',
      edificio: 'Edificio C',
      capacidad: 120,
      reservasHoy: 1,
      ocupadoActualmente: true,
    },
    {
      id: 'sp-lab-ia',
      nombre: 'Laboratorio Cómputo e IA',
      edificio: 'Ingenierías',
      capacidad: 40,
      reservasHoy: 4,
      ocupadoActualmente: true,
    },
    {
      id: 'sp-aula-magna',
      nombre: 'Aula Magna A-101',
      edificio: 'Edificio A',
      capacidad: 90,
      reservasHoy: 3,
      ocupadoActualmente: false,
    },
  ],
  evaluacionInversion: {
    capexTotal: 140000,
    capexDesglose: [
      { concepto: 'Desarrollo MVP & Pruebas', monto: 60000, descripcion: 'Ingeniería de software, autenticación y contratos inteligentes de actas' },
      { concepto: 'Infraestructura Cloud GCP (Año 1)', monto: 16000, descripcion: 'Cloud SQL PostgreSQL, Redis Memorystore, GCS y Cloud Run' },
      { concepto: 'Lectores Ópticos Industriales (3 Almacenes)', monto: 20000, descripcion: 'Hardware QR / código de barras Dell de uso rudo para ventanillas' },
      { concepto: 'Marco Legal, Privacidad & INDAUTOR', monto: 12000, descripcion: 'Aviso de Privacidad Ley General y depósito de derechos de autor' },
      { concepto: 'Señalética & Viáticos CUTonalá', monto: 12000, descripcion: 'Rotulación institucional, señalética QR y logística en campus' },
      { concepto: 'Fondo de Contingencia Operativa', monto: 20000, descripcion: 'Reserva para imprevistos técnicos o reabastecimiento de repuestos' }
    ],
    tmarPorcentaje: 15.0,
    vpnMxn: 23790.58,
    tirPorcentaje: 21.34,
    paybackMesesSimple: 29.6,
    paybackMesesDescontado: 34.0,
    puntoEquilibrioMeses: 15,
    relacionBeneficioCosto: 1.15,
    flujoTrienal: [
      { periodo: 'Año 0', fase: 'Inversión Inicial Semilla', planteles: 'Planeación & Setup', ingresos: 0, egresos: 140000, flujoNeto: -140000, flujoAcumulado: -140000 },
      { periodo: 'Año 1', fase: 'Piloto Controlado', planteles: 'CUTonalá (3 almacenes)', ingresos: 48000, egresos: 70000, flujoNeto: -22000, flujoAcumulado: -162000 },
      { periodo: 'Año 2', fase: 'Expansión Temática', planteles: 'CUTonalá + CUCEI', ingresos: 160000, egresos: 92000, flujoNeto: 68000, flujoAcumulado: -94000 },
      { periodo: 'Año 3', fase: 'Consolidación Red', planteles: '3 Centros + 1 Preparatoria', ingresos: 340000, egresos: 140000, flujoNeto: 200000, flujoAcumulado: 106000 }
    ],
    impactoPatrimonial: {
      reduccionMermasPorcentaje: 80,
      eliminacionEmpalmesPorcentaje: 100,
      tiempoDespachoSegundos: 28,
      tiempoDespachoAnteriorMinutos: 15,
      ahorroEstimadoMermasMxn: 148500
    }
  }
};
